/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-04-27 08:10:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/style-customer-header.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" body {\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	border: 1px solid lightblue;\r\n");
      out.write("	box-shadow: 0 5px 22px lightblue;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 99;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col1 {\r\n");
      out.write("	width: 24.8%;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col2 {\r\n");
      out.write("	width: 24.8%;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col3 {\r\n");
      out.write("	width: 24.8%;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col4 {\r\n");
      out.write("	width: 24.8%;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col1 img {\r\n");
      out.write("	width: 65%;\r\n");
      out.write("	height: 95px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .col1 img:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .sec-div .col2 a, .sec-div .col3 a, .sec-div .col4 a {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 23px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	width: 270px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	padding-top: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .sec-div .col2 a:hover, .sec-div .col3 a:hover {\r\n");
      out.write("	background-color: lightblue;\r\n");
      out.write("	border-radius: 2px 10em 50%;\r\n");
      out.write("	transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .sec-div .col4 a {\r\n");
      out.write("	background-color: lightblue;\r\n");
      out.write("	border-radius: 2px 10em 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-section .sec-div .col4 a:hover {\r\n");
      out.write("	background-color: #528B8B;\r\n");
      out.write("	color: white;\r\n");
      out.write("	transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<section class=\"header-section\" id=\"myHeader\">\r\n");
      out.write("			<div class=\"sec-div\">\r\n");
      out.write("				<div class=\"col1\">\r\n");
      out.write("					<a href=\"homepage\"><img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1681460706/capstoneproject/logo/logo_jpthaj.jpg\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col2\">\r\n");
      out.write("					<a href=\"information\" >BÁCH KHOA</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col3\">\r\n");
      out.write("					<a href=\"control\" >KIỂM SOÁT</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col4\">\r\n");
      out.write("					<a href=\"schedule\" >ĐẶT LỊCH TƯ VẤN</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
