/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-04-27 08:11:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"resources/css/style-customer-homepage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"hp-section1\">\r\n");
      out.write("	<div class=\"div1\">\r\n");
      out.write("		<div class=\"title\">\r\n");
      out.write("			<h2>BẢO VỆ<br/> <span>GIA ĐÌNH BẠN</span> <br/> KHỎI ĐỘNG VẬT GÂY HẠI</h2>\r\n");
      out.write("			<!-- <a href=\"\">Tư Vấn Miễn Phí </a> -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"img\">\r\n");
      out.write("			<img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1682071844/capstoneproject/customer/homepage/family3_corv2c.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hp-section2\">\r\n");
      out.write("	<div class=\"div1\">\r\n");
      out.write("		<div class=\"img\">\r\n");
      out.write("			<img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1682073585/capstoneproject/customer/homepage/control_vlg6yv.webp\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h6>Chúng Tôi Là Pest Control Service</h6>\r\n");
      out.write("			<h2><span>CHUYÊN GIA KIỂM SOÁT</span><br/> ĐỘNG VẬT GÂY HẠI</h2>\r\n");
      out.write("			<p>Không chỉ xua đuổi côn trùng, chúng tôi bảo vệ những giá trị mà gia đình Việt trân trọng nhất: \r\n");
      out.write("			nhà cửa, sức khỏe, hạnh phúc và cả sự an tâm.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hp-section3\">\r\n");
      out.write("	<div class=\"div1\">\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h2><span>CHĂM SÓC</span><br/> MỌI NGÔI NHÀ VIỆT</h2>\r\n");
      out.write("			<p>Không chỉ xua đuổi côn trùng, chúng tôi bảo vệ những giá trị mà gia đình Việt trân trọng nhất: \r\n");
      out.write("			nhà cửa, sức khỏe, hạnh phúc và cả sự an tâm.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"img\">\r\n");
      out.write("			<img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1682076138/capstoneproject/customer/homepage/homeinhand_vviqrt.jpg\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hp-section4\">\r\n");
      out.write("	<div class=\"div1\">\r\n");
      out.write("		<div class=\"img\">\r\n");
      out.write("			<img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1682212790/capstoneproject/homepage/me_z7b1q7.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h2><span>NGUYỄN HỮU HỒNG PHÚC</span></h2>\r\n");
      out.write("			<h6>(CEO Pest Control Service)</h6>\r\n");
      out.write("			<p>\"\"Đem đến cho khách hàng sự trải nghiệm và chất lượng hiệu quả là ưu tiên hàng đầu của chúng tôi.\r\n");
      out.write("			Sự hài lòng của bạn chính là động lực cho chúng tôi tiếp tục phát triển Pest Control Service.\"\"</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hp-section5\">\r\n");
      out.write("		<div class=\"s5-div1\">\r\n");
      out.write("			<div class=\"s5-d1-title\">\r\n");
      out.write("				<h2>BẠN ĐANG ĐAU ĐẦU <br/> VỚI<span> ĐÁM ĐỘNG VẬT GÂY HẠI</span> ĐÓ?<br/> HÃY LIÊN HỆ CHÚNG TÔI</h2>\r\n");
      out.write("				<a href=\"schedule\"><input type=\"submit\" value=\"LIÊN HỆ TƯ VẤN\"> </a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"s5-d1-image\">\r\n");
      out.write("				<img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1682221256/capstoneproject/homepage/headache_hyvw65.jpg\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
