/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-04-17 03:38:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class HorizontalMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>W3.CSS Template</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Lato\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/style-page-customer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/style-page-customer-main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/css.css\">\r\n");
      out.write("<style>\r\n");
      out.write("html,body,h1,h2,h3,h4 {margin-top:70px;\"Lato\", sans-serif}\r\n");
      out.write(".mySlides {display:none}\r\n");
      out.write(".w3-tag, .fa {cursor:pointer}\r\n");
      out.write(".w3-tag {height:15px;width:15px;padding:0;margin-top:6px}\r\n");
      out.write(".w3-top{\r\n");
      out.write("	box-shadow: 0 8px 7px lightgrey;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("	color: #333399;\r\n");
      out.write("	margin-left: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu{\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#img-logo{\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Links (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\" >\r\n");
      out.write("  <div class=\"w3-row w3-large w3-light-grey\"  style=\"background-color: white\">\r\n");
      out.write("    <div class=\"w3-col s3\" id=\"img-logo\">\r\n");
      out.write("      <a href=\"#\" class=\"w3-button w3-block\"><img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1681460706/capstoneproject/logo/logo_jpthaj.jpg\" height=\"80v\" width=\"50%\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col s3\" >\r\n");
      out.write("      <a href=\"#plans\" id=\"menu\" class=\"w3-button w3-block\"  style=\"background-color: white\">Bách Khoa</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col s3\">\r\n");
      out.write("      <a href=\"#about\" id=\"menu\" class=\"w3-button w3-block\" style=\"background-color: white\">Kiểm Soát</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col s3\">\r\n");
      out.write("      <a href=\"#contact\" id=\"menu\" class=\"w3-button w3-block\" style=\"background-color: lightblue; border-radius: 2px 10em 50%\">Đặt Lịch Tư Vấn</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Content -->\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:1100px;margin-top:80px;margin-bottom:80px\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-panel\">\r\n");
      out.write("    <h1><b>BẢO VỆ GIA ĐÌNH BẠN KHỎI ĐỘNG VẬT GÂY HẠI</b></h1>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Slideshow -->\r\n");
      out.write("  <div class=\"w3-container\" >\r\n");
      out.write("    <div class=\"w3-display-container mySlides\" >\r\n");
      out.write("      <img src=\"https://res.cloudinary.com/dedbfm0dk/image/upload/v1681441970/capstoneproject/customer/slide1_pxh61f.png\" style=\"height:70vh;width:100%\">\r\n");
      out.write("      <!-- <div class=\"w3-display-topleft w3-container w3-padding-32\">\r\n");
      out.write("        <span class=\"w3-white w3-padding-large w3-animate-bottom\">Lorem ipsum</span>\r\n");
      out.write("      </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-display-container mySlides\">\r\n");
      out.write("      <img src=\"\" style=\"width:100%\">\r\n");
      out.write("      <!-- <div class=\"w3-display-middle w3-container w3-padding-32\">\r\n");
      out.write("        <span class=\"w3-white w3-padding-large w3-animate-bottom\">Klorim tipsum</span>\r\n");
      out.write("      </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-display-container mySlides\">\r\n");
      out.write("      <img src=\"/w3images/sound.jpg\" style=\"width:100%\">\r\n");
      out.write("      <!-- <div class=\"w3-display-topright w3-container w3-padding-32\">\r\n");
      out.write("        <span class=\"w3-white w3-padding-large w3-animate-bottom\">Blorum pipsum</span>\r\n");
      out.write("      </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slideshow next/previous buttons -->\r\n");
      out.write("    <div class=\"w3-container w3-dark-grey w3-padding w3-xlarge\">\r\n");
      out.write("      <div class=\"w3-left\" onclick=\"plusDivs(-1)\"><i class=\"fa fa-arrow-circle-left w3-hover-text-teal\"></i></div>\r\n");
      out.write("      <div class=\"w3-right\" onclick=\"plusDivs(1)\"><i class=\"fa fa-arrow-circle-right w3-hover-text-teal\"></i></div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"w3-center\">\r\n");
      out.write("        <span class=\"w3-tag demodots w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(1)\"></span>\r\n");
      out.write("        <span class=\"w3-tag demodots w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(2)\"></span>\r\n");
      out.write("        <span class=\"w3-tag demodots w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(3)\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Grid -->\r\n");
      out.write("  <div class=\"w3-row w3-container\">\r\n");
      out.write("    <div class=\"w3-center w3-padding-64\">\r\n");
      out.write("      <span class=\"w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16\">Chúng Tôi Cung Cấp</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-light-grey w3-container w3-padding-16\" style=\"background-color: grey\">\r\n");
      out.write("      <h3>Tư Vấn</h3>\r\n");
      out.write("      <p>Chúng tôi sẽ liên lạc với bạn để trả lời những thắc mắc của bạn về động vật gây hại.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-grey w3-container w3-padding-16\">\r\n");
      out.write("      <h3>Khảo Sát</h3>\r\n");
      out.write("      <p>Chúng tôi sẽ đến nơi bạn cung cấp để khảo sát những vấn đề bạn đang gặp phải tại đó.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-dark-grey w3-container w3-padding-16\">\r\n");
      out.write("      <h3>Lên Kế Hoạch</h3>\r\n");
      out.write("      <p>Sau khi khảo sát, chúng tôi sẽ lên kế hoạch thực hiện và triển khai kế hoạch đó.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-col l3 m6 w3-black w3-container w3-padding-16\">\r\n");
      out.write("      <h3>Sự Đảm Bảo</h3>\r\n");
      out.write("      <p>Chúng tôi đảm các giải pháp sẽ thực hiện trong thời gian ngắn nhất và hiệu quả nhất.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Grid -->\r\n");
      out.write("  <!-- <div class=\"w3-row-padding\" id=\"plans\">\r\n");
      out.write("    <div class=\"w3-center w3-padding-64\">\r\n");
      out.write("      <h3>Pricing Plans</h3>\r\n");
      out.write("      <p>Choose a pricing plan that fits your needs.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <ul class=\"w3-ul w3-border w3-center w3-hover-shadow\">\r\n");
      out.write("        <li class=\"w3-black w3-xlarge w3-padding-32\">Basic</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>10GB</b> Storage</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>10</b> Emails</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>10</b> Domains</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>Endless</b> Support</li>\r\n");
      out.write("        <li class=\"w3-padding-16\">\r\n");
      out.write("          <h2 class=\"w3-wide\">$ 10</h2>\r\n");
      out.write("          <span class=\"w3-opacity\">per month</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("          <button class=\"w3-button w3-green w3-padding-large\">Sign Up</button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <ul class=\"w3-ul w3-border w3-center w3-hover-shadow\">\r\n");
      out.write("        <li class=\"w3-dark-grey w3-xlarge w3-padding-32\">Pro</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>25GB</b> Storage</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>25</b> Emails</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>25</b> Domains</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>Endless</b> Support</li>\r\n");
      out.write("        <li class=\"w3-padding-16\">\r\n");
      out.write("          <h2 class=\"w3-wide\">$ 25</h2>\r\n");
      out.write("          <span class=\"w3-opacity\">per month</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("          <button class=\"w3-button w3-green w3-padding-large\">Sign Up</button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <ul class=\"w3-ul w3-border w3-center w3-hover-shadow\">\r\n");
      out.write("        <li class=\"w3-black w3-xlarge w3-padding-32\">Premium</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>50GB</b> Storage</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>50</b> Emails</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>50</b> Domains</li>\r\n");
      out.write("        <li class=\"w3-padding-16\"><b>Endless</b> Support</li>\r\n");
      out.write("        <li class=\"w3-padding-16\">\r\n");
      out.write("          <h2 class=\"w3-wide\">$ 50</h2>\r\n");
      out.write("          <span class=\"w3-opacity\">per month</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("          <button class=\"w3-button w3-green w3-padding-large\">Sign Up</button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Grid -->\r\n");
      out.write("  <div class=\"w3-row-padding\" id=\"about\">\r\n");
      out.write("    <div class=\"w3-center w3-padding-64\">\r\n");
      out.write("      <span class=\"w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16\">Who We Are</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <div class=\"w3-card-4\">\r\n");
      out.write("        <img src=\"/w3images/team1.jpg\" alt=\"John\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"w3-container\">\r\n");
      out.write("          <h3>Jane Doe</h3>\r\n");
      out.write("          <p class=\"w3-opacity\">CEO & Founder</p>\r\n");
      out.write("          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>\r\n");
      out.write("          <p><button class=\"w3-button w3-light-grey w3-block\">Contact</button></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <div class=\"w3-card-4\">\r\n");
      out.write("        <img src=\"/w3images/team2.jpg\" alt=\"Mike\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"w3-container\">\r\n");
      out.write("          <h3>Mike Ross</h3>\r\n");
      out.write("          <p class=\"w3-opacity\">Art Director</p>\r\n");
      out.write("          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>\r\n");
      out.write("          <p><button class=\"w3-button w3-light-grey w3-block\">Contact</button></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-third w3-margin-bottom\">\r\n");
      out.write("      <div class=\"w3-card-4\">\r\n");
      out.write("        <img src=\"/w3images/team3.jpg\" alt=\"Jane\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"w3-container\">\r\n");
      out.write("          <h3>John Doe</h3>\r\n");
      out.write("          <p class=\"w3-opacity\">Designer</p>\r\n");
      out.write("          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>\r\n");
      out.write("          <p><button class=\"w3-button w3-light-grey w3-block\">Contact</button></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact -->\r\n");
      out.write("  <div class=\"w3-center w3-padding-64\" id=\"contact\">\r\n");
      out.write("    <span class=\"w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16\">Contact Us</span>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <form class=\"w3-container\" action=\"/action_page.php\" target=\"_blank\">\r\n");
      out.write("    <div class=\"w3-section\">\r\n");
      out.write("      <label>Name</label>\r\n");
      out.write("      <input class=\"w3-input w3-border w3-hover-border-black\" style=\"width:100%;\" type=\"text\" name=\"Name\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-section\">\r\n");
      out.write("      <label>Email</label>\r\n");
      out.write("      <input class=\"w3-input w3-border w3-hover-border-black\" style=\"width:100%;\" type=\"text\" name=\"Email\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-section\">\r\n");
      out.write("      <label>Subject</label>\r\n");
      out.write("      <input class=\"w3-input w3-border w3-hover-border-black\" style=\"width:100%;\" name=\"Subject\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"w3-section\">\r\n");
      out.write("      <label>Message</label>\r\n");
      out.write("      <input class=\"w3-input w3-border w3-hover-border-black\" style=\"width:100%;\" name=\"Message\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"submit\" class=\"w3-button w3-block w3-black\">Send</button>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"w3-container w3-padding-32 w3-light-grey w3-center\">\r\n");
      out.write("  <h4>Footer</h4>\r\n");
      out.write("  <a href=\"#\" class=\"w3-button w3-black w3-margin\"><i class=\"fa fa-arrow-up w3-margin-right\"></i>To the top</a>\r\n");
      out.write("  <div class=\"w3-xlarge w3-section\">\r\n");
      out.write("    <i class=\"fa fa-facebook-official w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-instagram w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-snapchat w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-pinterest-p w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-twitter w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-linkedin w3-hover-opacity\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" title=\"W3.CSS\" target=\"_blank\" class=\"w3-hover-text-green\">w3.css</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Slideshow\r\n");
      out.write("var slideIndex = 1;\r\n");
      out.write("showDivs(slideIndex);\r\n");
      out.write("\r\n");
      out.write("function plusDivs(n) {\r\n");
      out.write("  showDivs(slideIndex += n);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function currentDiv(n) {\r\n");
      out.write("  showDivs(slideIndex = n);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showDivs(n) {\r\n");
      out.write("  var i;\r\n");
      out.write("  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("  var dots = document.getElementsByClassName(\"demodots\");\r\n");
      out.write("  if (n > x.length) {slideIndex = 1}    \r\n");
      out.write("  if (n < 1) {slideIndex = x.length} ;\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].style.display = \"none\";  \r\n");
      out.write("  }\r\n");
      out.write("  for (i = 0; i < dots.length; i++) {\r\n");
      out.write("    dots[i].className = dots[i].className.replace(\" w3-white\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("  x[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("  dots[slideIndex-1].className += \" w3-white\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
